okx fetchCurrencies Math.whatever -> Precise
ccxt/ccxt pull request #14714
Opened 2022-08-17 06:29 UTC by samgermain

```
2022-08-17T06:25:16.409Z
Node.js: v18.4.0
CCXT v1.92.30
okx.fetchCurrencies ()
2022-08-17T06:25:18.364Z iteration 0 passed in 548 ms

{
  USDT: {
    info: undefined,
    code: 'USDT',
    id: 'USDT',
    name: 'Tether',
    active: false,
    deposit: true,
    withdraw: false,
    fee: undefined,
    precision: '0.0001',
    limits: { amount: { min: undefined, max: undefined } },
    networks: {
      TRC20: {
        id: 'USDT-TRC20',
        network: 'TRC20',
        active: true,
        deposit: true,
        withdraw: true,
        fee: 0.8,
        precision: 0.0001,
        limits: { withdraw: { min: 2, max: 12186550 } },
        info: {
          canDep: true,
          canInternal: true,
          canWd: true,
          ccy: 'USDT',
          chain: 'USDT-TRC20',
          logoLink: 'https://static.coinall.ltd/cdn/assets/imgs/221/5F74EB20302D7761.png',
          mainNet: false,
          maxFee: '1.6',
          maxWd: '12186550',
          minDep: '0.00000001',
          minDepArrivalConfirm: '1',
          minFee: '0.8',
          minWd: '2',
          minWdUnlockConfirm: '1',
          name: 'Tether',
          needTag: false,
          usedWdQuota: '0',
          wdQuota: '10',
          wdTickSz: '4'
        }
      },
      ERC20: {
        id: 'USDT-ERC20',
        network: 'ERC20',
        active: true,
        deposit: true,
        withdraw: true,
        fee: 4.5408104,
        precision: 0.0001,
        limits: { withdraw: { min: 2, max: 4874620 } },
        info: {
          canDep: true,
          canInternal: true,
          canWd: true,
          ccy: 'USDT',
          chain: 'USDT-ERC20',
          logoLink: 'https://static.coinall.ltd/cdn/assets/imgs/221/5F74EB20302D7761.png',
          mainNet: false,
          maxFee: '9.0816208',
          maxWd: '4874620',
          minDep: '0.00000001',
          minDepArrivalConfirm: '12',
          minFee: '4.5408104',
          minWd: '2',
          minWdUnlockConfirm: '30',
          name: 'Tether',
          needTag: false,
          usedWdQuota: '0',
          wdQuota: '10',
          wdTickSz: '4'
        }
      },
      USDT: {
        id: 'USDT-Omni',
        network: 'USDT',
        active: false,
        deposit: false,
        withdraw: false,
        fee: 0.0002,
        precision: 0.0001,
        limits: { withdraw: { min: 10, max: 12186550 } },
        info: {
          canDep: false,
          canInternal: true,
          canWd: false,
          ccy: 'USDT',
          chain: 'USDT-Omni',
          logoLink: 'https://static.coinall.ltd/cdn/assets/imgs/221/5F74EB20302D7761.png',
          mainNet: true,
          maxFee: '0.0004',
          maxWd: '12186550',
          minDep: '1',
          minDepArrivalConfirm: '1',
          minFee: '0.0002',
          minWd: '10',
          minWdUnlockConfirm: '3',
          name: 'Tether',
          needTag: false,
          usedWdQuota: '0',
          wdQuota: '10',
          wdTickSz: '4'
        }
      },
      Liquid: {
        id: 'USDT-Liquid',
        network: 'Liquid',
        active: false,
        deposit: false,
        withdraw: false,
        fee: 0,
        precision: 0.0001,
        limits: { withdraw: { min: 0.1, max: 4874620 } },
        info: {
          canDep: false,
          canInternal: true,
          canWd: false,
          ccy: 'USDT',
          chain: 'USDT-Liquid',
          logoLink: 'https://static.coinall.ltd/cdn/assets/imgs/221/5F74EB20302D7761.png',
          mainNet: false,
          maxFee: '1',
          maxWd: '4874620',
          minDep: '0.00000001',
          minDepArrivalConfirm: '6',
          minFee: '0',
          minWd: '0.1',
          minWdUnlockConfirm: '10',
          name: 'Tether',
          needTag: false,
          usedWdQuota: '0',
          wdQuota: '10',
          wdTickSz: '4'
        }
      },
      OKExChain_KIP10: {
        id: 'USDT-OKExChain_KIP10',
        network: 'OKExChain_KIP10',
        active: false,
        deposit: false,
        withdraw: false,
        fee: 0,
        precision: 0.0001,
        limits: { withdraw: { min: 0, max: 2437310 } },
        info: {
          canDep: false,
          canInternal: true,
          canWd: false,
          ccy: 'USDT',
          chain: 'USDT-OKExChain_KIP10',
          logoLink: 'https://static.coinall.ltd/cdn/assets/imgs/221/5F74EB20302D7761.png',
          mainNet: false,
          maxFee: '0',
          maxWd: '2437310',
          minDep: '0.00000001',
          minDepArrivalConfirm: '2',
          minFee: '0',
          minWd: '0',
          minWdUnlockConfirm: '4',
          name: 'Tether',
          needTag: false,
          usedWdQuota: '0',
          wdQuota: '10',
          wdTickSz: '4'
        }
      },
      OKC: {
        id: 'USDT-OKC',
        network: 'OKC',
        active: true,
        deposit: true,
        withdraw: true,
        fee: 0,
        precision: 0.0001,
        limits: { withdraw: { min: 1, max: 2437310 } },
        info: {
          canDep: true,
          canInternal: true,
          canWd: true,
          ccy: 'USDT',
          chain: 'USDT-OKC',
          logoLink: 'https://static.coinall.ltd/cdn/assets/imgs/221/5F74EB20302D7761.png',
          mainNet: false,
          maxFee: '0',
          maxWd: '2437310',
          minDep: '0.00000001',
          minDepArrivalConfirm: '2',
          minFee: '0',
          minWd: '1',
          minWdUnlockConfirm: '4',
          name: 'Tether',
          needTag: false,
          usedWdQuota: '0',
          wdQuota: '10',
          wdTickSz: '4'
        }
      },
      Polygon: {
        id: 'USDT-Polygon',
        network: 'Polygon',
        active: true,
        deposit: true,
        withdraw: true,
        fee: 0.64,
        precision: 0.0001,
        limits: { withdraw: { min: 0.01, max: 2437310 } },
        info: {
          canDep: true,
          canInternal: true,
          canWd: true,
          ccy: 'USDT',
          chain: 'USDT-Polygon',
          logoLink: 'https://static.coinall.ltd/cdn/assets/imgs/221/5F74EB20302D7761.png',
          mainNet: false,
          maxFee: '1.28',
          maxWd: '2437310',
          minDep: '0.00000001',
          minDepArrivalConfirm: '130',
          minFee: '0.64',
          minWd: '0.01',
          minWdUnlockConfirm: '200',
          name: 'Tether',
          needTag: false,
          usedWdQuota: '0',
          wdQuota: '10',
          wdTickSz: '4'
        }
      },
      Solana: {
        id: 'USDT-Solana',
        network: 'Solana',
        active: true,
        deposit: true,
        withdraw: true,
        fee: 0.8,
        precision: 0.0001,
        limits: { withdraw: { min: 0.1, max: 2437310 } },
        info: {
          canDep: true,
          canInternal: true,
          canWd: true,
          ccy: 'USDT',
          chain: 'USDT-Solana',
          logoLink: 'https://static.coinall.ltd/cdn/assets/imgs/221/5F74EB20302D7761.png',
          mainNet: false,
          maxFee: '1.6',
          maxWd: '2437310',
          minDep: '0.00000001',
          minDepArrivalConfirm: '200',
          minFee: '0.8',
          minWd: '0.1',
          minWdUnlockConfirm: '200',
          name: 'Tether',
          needTag: false,
          usedWdQuota: '0',
          wdQuota: '10',
          wdTickSz: '4'
        }
      },
      'Avalanche C': {
        id: 'USDT-Avalanche C-Chain',
        network: 'Avalanche C',
        active: true,
        deposit: true,
        withdraw: true,
        fee: 0.8,
        precision: 0.0001,
        limits: { withdraw: { min: 0.01, max: 2437310 } },
        info: {
          canDep: true,
          canInternal: true,
          canWd: true,
          ccy: 'USDT',
          chain: 'USDT-Avalanche C-Chain',
          logoLink: 'https://static.coinall.ltd/cdn/assets/imgs/221/5F74EB20302D7761.png',
          mainNet: false,
          maxFee: '1.6',
          maxWd: '2437310',
          minDep: '0.00000001',
          minDepArrivalConfirm: '30',
          minFee: '0.8' [...]

2022-08-18 13:26 UTC, carlosmiei requested changes
missing conversion

2022-08-24 08:15 UTC, samgermain commented on js/okx.js
> +                        maxPrecision = Precise.stringMax (maxPrecision, precision);
if I do the conversion here, then `stringMax` will be comparing a number and a string

2022-08-26 11:20 UTC, carlosmiei commented
LGTM ✅ 
```
Python v3.9.7
CCXT v1.92.59
okx.fetchCurrencies()
{'1INCH': {'active': False,
           'code': '1INCH',
           'deposit': True,
           'fee': None,
           'id': '1INCH',
           'info': None,
           'limits': {'amount': {'max': None, 'min': None}},
           'name': '1inch',
           'networks': {'1INCH': {'active': True,
                                  'deposit': True,
                                  'fee': 5.48973116,
                                  'id': '1INCH-ERC20',
                                  'info': {'canDep': True,
                                           'canInternal': True,
                                           'canWd': True,
                                           'ccy': '1INCH',
                                           'chain': '1INCH-ERC20',
                                           'logoLink': 'https://static.coinall.ltd/cdn/assets/imgs/2012/CC3825464672C7DD.png',
                                           'mainNet': True,
                                           'maxFee': '10.97946232',
                                           'maxWd': '8927528',
                                           'minDep': '0.00000001',
                                           'minDepArrivalConfirm': '12',
                                           'minFee': '5.48973116',
                                           'minWd': '1',
                                           'minWdUnlockConfirm': '30',
                                           'name': '1inch',
                                           'needTag': False,
                                           'usedWdQuota': '0',
                                           'wdQuota': '200',
                                           'wdTickSz': '4'},
                                  'limits': {'withdraw': {'max': 8927528.0,
                                                          'min': 1.0}},
                                  'network': '1INCH',
                                  'precision': 0.0001,
                                  'withdraw': True}},
           'precision': 0.0001,
           'withdraw': True}
```

2022-08-26 11:21 UTC, carlosmiei approved these changes

2022-08-26 11:40 UTC, merged