fetchOpenInterestHistory: adjust open interest structure
ccxt/ccxt pull request #15088
Opened 2022-09-23 04:37 UTC by Dan-krm

Adjusted the open interest structure across current exchanges that have the fetchOpenInterestHistory method.

Currently the structure is:
```
{
    symbol: 'BTC/USDT',
    baseVolume: 80872.801,
    quoteVolume: 3508262107.38,
    timestamp: 1649379000000,
    datetime: '2022-04-08T00:50:00.000Z',
    info: {
        symbol: 'BTCUSDT',
        sumOpenInterest: '80872.80100000',
        sumOpenInterestValue: '3508262107.38000000',
        timestamp: '1649379000000'
    }
}
```

This PR changes it to:
```
{
    symbol: 'BTC/USDT',
    openInterestAmount: 80872.801,
    openInterestValue: 3508262107.38,
    timestamp: 1649379000000,
    datetime: '2022-04-08T00:50:00.000Z',
    info: {
        symbol: 'BTCUSDT',
        sumOpenInterest: '80872.80100000',
        sumOpenInterestValue: '3508262107.38000000',
        timestamp: '1649379000000'
    }
}
```

2022-09-26 15:31 UTC, carlosmiei commented on js/bybit.js
> +            'openInterestValue': Precise.stringMul (numContracts, contractSize),
@Dan-krm we should be converting this to a number

2022-10-04 16:01 UTC, carlosmiei commented on js/binance.js
> +            'baseVolume': this.safeNumber (interest, 'sumOpenInterest'),  // deprecated
Can we avoid calling `safeNumber` twice with the same value?

2022-10-04 16:01 UTC, carlosmiei commented on js/bybit.js
> +            'baseVolume': Precise.stringMul (numContracts, contractSize),  // deprecated
We should be converting `baseVolume` to number here

2022-10-04 16:02 UTC, carlosmiei commented on js/huobi.js
> +            'baseVolume': this.safeNumber (interest, 'volume'),  // deprecated
same, avoid duplicated `safeNumber` calls pls

2022-10-10 19:23 UTC, samgermain requested changes

2022-10-10 19:23 UTC, samgermain commented on doc/manual.rst
> +       openInterestValue: 3508262107.38,
These changes should be made to `wiki/manual.md`, not `doc/manual.rst`

2022-10-20 02:19 UTC, Dan-krm commented
> **aax** and **ftx** should also be updated

**aax** and **ftx** only have fetchOpenInterest so there is nothing to update in this PR

2022-10-24 11:23 UTC, carlosmiei commented
LGTM ✅ 

```
p bybit fetchOpenInterestHistory "BTC/USDT:USDT" 1h None 1 --sandbox
Python v3.10.6
CCXT v2.0.61
bybit.fetchOpenInterestHistory(BTC/USDT:USDT,1h,None,1)
[{'baseVolume': 86055.738,
  'datetime': '1970-01-20T06:56:49.200Z',
  'info': {'open_interest': '86055.738',
           'symbol': 'BTCUSDT',
           'timestamp': '1666609200'},
  'openInterestAmount': None,
  'openInterestValue': 86055.738,
  'quoteVolume': None,
  'symbol': 'BTC/USDT:USDT',
  'timestamp': 1666609200}]
```

2022-10-24 11:25 UTC, carlosmiei approved these changes

2022-10-24 11:41 UTC, merged