bibox createOrderV4
ccxt/ccxt pull request #15278
Opened 2022-10-13 15:15 UTC by ndubel

https://biboxcom.github.io/v3/spotv4/en/#create-an-order
it's not possible to create order with amount over 1000000 using v1 method 
`InvalidOrder bibox {"result":[{"error":{"code":"2131","msg":"下单数量不能大于"},"cmd":"orderpending/trade"}],"error":{"code":"2131","msg":"下单数量不能大于"},"cmd":"orderpending/trade"}`
but it all ok in v4 method

The similar error with precision - when I try to create order for example on `LUNC/USDT` and price `0.0002500001` it creates correctly but with price `0.00025`. It works correctly in v4 method

2022-10-13 16:41 UTC, carlosmiei commented
@ndubel thanks, we will review it soon!

2022-10-14 00:23 UTC, samgermain requested changes

2022-10-14 00:23 UTC, samgermain commented on js/bibox.js
> +    async createOrderV1 (symbol, type, side, amount, price = undefined, params = {}) {
we Could just get rid of this method

2022-10-14 00:23 UTC, samgermain commented on js/bibox.js
> +        const clientOrderId = this.safeString2 (params, 'client_order_id', 'clientOrderId');
remove `client_order_id` and just make it `safeString`. `client_order_id` will end up in the request params anyway

------

Also add `clientOrderId` to the docstring as `params.clientOrderId`

2022-10-14 00:23 UTC, samgermain commented on js/bibox.js
> +            params = this.omit (params, [ 'client_order_id', 'clientOrderId' ]);
make sure to take `client_order_id` out of this too

2022-10-14 00:23 UTC, samgermain commented on js/bibox.js
> +        //
can you add a space character after all the `:`

So it'd be

```
//     {
        //         "i": 14580623695947906,
        //         "I": "0",
        //         "m": "LUNC_USDT",
```

2022-10-14 00:23 UTC, samgermain commented on js/bibox.js
> +        //         "status":3                  // Status,-1-fail, 0,1-to be dealt, 2-dealt partly, 3-dealt totally, 4- cancelled partly, 5-cancelled totally, 6-to be cancelled
add spaces after the `:`

2022-10-14 00:23 UTC, samgermain commented on js/bibox.js
> +        //                 }
Make sure the `}` line up

2022-10-17 13:23 UTC, ndubel commented
please check again

2022-10-17 15:42 UTC, carlosmiei commented on js/bibox.js
> +        const postOnly = this.safeValue (order, 'o');
I think we need to adjust `fee` parsing as well 
![image](https://user-images.githubusercontent.com/43336371/196222023-9df90eba-5df5-42b4-942d-0175125700ed.png)

2022-10-18 11:13 UTC, carlosmiei commented
LGTM ✅ 

```
n bibox createOrder LTC/USDT limit sell 0.09 90

{
  info: {
    i: '14580623696139950',
    I: '0',
    m: 'LTC_USDT',
    T: 'limit',
    s: 'sell',
    Q: '-0.09000000',
    P: '90.0000',
    t: 'gtc',
    o: false,
    S: 'accepted',
    E: '0',
    e: '0',
    C: '1666090926932',
    U: '1666090926932',
    V: '585893685335',
    n: '0',
    F: [],
    f: []
  },
  id: '14580623696139950',
  clientOrderId: undefined,
  timestamp: 1666090926932,
  datetime: '2022-10-18T11:02:06.932Z',
  lastTradeTimestamp: undefined,
  symbol: 'LTC/USDT',
  type: 'limit',
  timeInForce: 'gtc',
  postOnly: false,
  side: 'sell',
  price: 90,
  stopPrice: undefined,
  amount: 0.09,
  cost: undefined,
  average: undefined,
  filled: undefined,
  remaining: undefined,
  status: 'open',
  fee: undefined,
  fees: [],
  trades: []
}
```

```
 n bibox fetchClosedOrders "LTC/USDT" undefined 1          

               id | clientOrderId |     timestamp |                 datetime | lastTradeTimestamp |   symbol |   type | timeInForce | postOnly | side | price | stopPrice | amount | cost | average | filled | remaining |   status | fee | fees | trades
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
14580623696139913 |               | 1666090865751 | 2022-10-18T11:01:05.751Z |                    | LTC/USDT | market |         IOC |          | sell |    90 |           |    0.1 |    9 |         |      0 |       0.1 | rejected |     |   [] |     []
1 objects
2022-10-18T11:11:55.925Z iteration 1 passed in 444 ms
```

2022-10-18 11:14 UTC, carlosmiei approved these changes

2022-10-18 11:30 UTC, merged