Fix build_ohlcvc with single trade
ccxt/ccxt pull request #17816
Opened 2023-05-06 15:43 UTC by carlosmiei

- continues https://github.com/ccxt/ccxt/pull/17721/files

2023-05-06 19:31 UTC, auchri requested changes
typo :)

2023-05-07 08:17 UTC, auchri requested changes

2023-05-07 08:17 UTC, auchri commented on ts/src/base/functions/misc.ts
> +    for (let i = 0; i < oldest; i++) {{
typo :)

2023-05-07 09:46 UTC, carlosmiei commented on ts/src/base/functions/misc.ts
> +    for (let i = 0; i < oldest; i++) {{
@auchri you're right 🤦 , thanks! 🙂

2023-05-07 11:22 UTC, merged