tests - add network tests
ccxt/ccxt pull request #18594
Opened 2023-07-18 17:27 UTC by ttodua

2026-05-27 05:44 UTC, ttodua commented
@carlosmiei ready ^

2026-06-08 10:01 UTC, ttodua commented
@carlosmiei ^

2026-07-06 17:50 UTC, ttodua commented on ts/src/test/Exchange/base/test.currency.ts
> +    const baseFormat = {
expected

2026-07-06 17:51 UTC, ttodua commented on ts/src/test/Exchange/base/test.currency.ts
> +        if (networkKeysLength === 0 && ('skipCurrenciesWithoutNetworks' in skippedProperties)) {
deliberate

2026-07-06 18:04 UTC, ttodua commented on ts/src/test/Exchange/base/test.currency.ts
>          } else {
intended design

2026-07-20 19:06 UTC, ttodua commented
@kroitor you have closed & reopened this topic, maybe ready to merge?

2026-09-13 21:27 UTC, carlotestor requested changes
## Review — PR #18594 (head `46dd1b9af9a1a3e4a710965ebf57a728a02913d9`)

Verified in a throwaway worktree; `/root/ccxt` untouched. This is a **shared base test** (`ts/src/test/Exchange/base/test.currency.ts`) so every assertion here fires for every exchange in every language — it earns matrix-wide evidence, not a diff read.

Merge gate: 🔴

**Category: REBASE — and substantively WRONG APPROACH at this head.** The conflict is trivial to resolve, but the resolved content fails broadly across the matrix in both JS and Python.

### 1. What conflicts

```
$ git merge-tree --write-tree origin/master 46dd1b9
CONFLICT (content): Merge conflict in ts/src/test/Exchange/base/test.currency.ts
```

Single file, whole-function conflict. Merge base is `9d892b68dbb6a59ce231e8916503d3a5718904bc` (2026-07-06), **3178 commits** behind `origin/master`. Both sides rewrote the same region: master's `testCurrency` gained an `isNative` triple-guard (`!== undefined && !== false && !== 'emulated'`), a `Dict` type annotation, and the `skipCurrenciesWithoutNetworks` early return; the PR replaces the entire body with `baseFormat` / `currencyFormat` / `networkFormat` + a new `helperTestSharedCurrencyFormat`. There is no salvageable non-conflicting hunk — it is a full-file replacement.

### 2. Is it already landed?

**Partly, and the parts that landed are the low-risk parts.** `assertValidCurrencyIdAndCode` — one of this PR's headline moves — is already on master (it sits inside the `limits` block at the tail of `testCurrency`). The rest of master's evolution went the *opposite* direction from this PR:

| master commit | effect |
|---|---|
| `19ef48fb4f5` tests(fetchCurrencies): make active/deposit/withdraw checks robust (#25723) | this is the *same problem area* the PR's new `active` invariant re-enters — master already settled it differently |
| `660f5e207d1` test(currency) — leveraged tokens tests | added the `leveraged`/`other` precision carve-out |
| `2d6fdb2bf5b` test(currency): allow numeric id too (#27769) | the `"id" key` retry path |
| `4a96d918521` / `023c4fcf564` / `174ef82ccfd` | strictNullChecks, noImplicitAny, strict-boolean-expressions |

So the PR is not superseded wholesale, but its useful delta has shrunk to "recurse into `networks[]`", and it would revert three years of hardening to get there.

### 3. Would it pass across the matrix?

No. I applied the PR's file verbatim onto current master and ran `testCurrency` over all **89** offline currency fixtures in `ts/src/test/static/currencies/`, seeded via `exchange.currencies` / `currencies_by_id`, honouring each exchange's `skip-tests.json` `fetchCurrencies` skips — master baseline vs PR head, same harness both legs.

**JS lane**

| leg | failing exchanges | failing currency entries |
|---|---|---|
| master (baseline) | 21 | 103 |
| PR head | **60** | **334** |

**39 exchanges newly red** that are green on master:

`alpaca aster bequant binance bit2c bitbns bitfinex bithumb bitso bittrade blockchaincom blofin bybit cex coinex coinmate coinone deepcoin delta derive digifinex dydx gate grvt hashkey htx independentreserve indodax krakenfutures kucoin mexc nado p2b paradex phemex tokocrypto upbit weex woo`

**Python lane** — regenerated with `npx tsx build/transpile.ts --test --force` per leg (note: `--baseTests` returns early *before* `ts/src/test/Exchange/base/`, so it leaves `test_currency.py` stale — a false green; I confirmed `grep -c helper_test_shared_currency_format python/ccxt/test/exchange/base/test_currency.py` = **0** after revert, **3** after apply, in PHP too, before trusting either number):

| leg | failing exchanges | failing currency entries |
|---|---|---|
| master | 49 | 294 |
| PR head | **81 / 89** | **522** |

34 exchanges newly red in Python. Python is *worse* than JS, which is the tell for a cross-language defect rather than a fixture problem.

#### The three failure classes

**(a) Hard crash on a null network entry — 10 exchanges.** The PR deletes master's `if (entry === undefined) return;` guard and replaces `exchange.safeDict (entry, 'networks', {})` with a raw `entry['networks']`, then `Object.keys()` on it:

```
deribit / derive / grvt / phemex:  TypeError: Cannot convert undefined or null to object
hibachi / lighter / aster / apex / bitso / bittrade:  TypeError: Cannot use 'in' operator to search for 'network' in null
```

This is exactly the JS-`undefined` vs Python/C#-`null` asymmetry: an exchange whose `networks` is absent yields `undefined` in JS and `None` in Python, and neither survives the unguarded `Object.keys`/`in`. Python reports the same rows as `[AssertionError] item is null/undefined`. `safeDict(..., {})` existed on master precisely to absorb this.

**(b) The new `active` invariant is not true of the data — 19 exchanges.** 

```js
if (entry['deposit'] === true && entry['withdraw'] === true) {
    assert (entry['active'] === true, 'active must be true if deposit and withdraw are both true');
}
```

Fails on `bequant binance bingx bitfinex bybit cex coinex coinone digifinex gate hashkey htx mexc nado okx toobit weex whitebit woo` — all green on master. These parsers legitimately emit `deposit: true, withdraw: true, active: undefined`, and `undefined !== true`. The assertion needs to tolerate an unset `active` (and in Python/C# a real `null`) or it reds ~20% of the matrix on day one. Master's #25723 already made this check robust; this reintroduces the strict form.

**(c) `info` / `precision` / `network` now mandatory unconditionally.** By folding `'info': {}` and `'precision'` into `baseFormat` — outside the `isNative` guard master keeps them behind — emulated-`fetchCurrencies` exchanges fail `"info" key is missing from structure` (`luno p2b paradex tokocrypto krakenfutures independentreserve kucoinfutures dydx upbit`). And `networkFormat` requires `'network'` on every network entry, which `kucoin` (12/12) does not carry.

#### Compile gate

The file does not typecheck against today's `tsconfig.json` either. Unpatched master baseline is **7** pre-existing `error TS` (all in `Exchange.ts`/`hibachi.ts`, **0** in `test.currency.ts`); with the PR's file applied, **7 new errors land in `test.currency.ts`**:

```
ts/src/test/Exchange/base/test.currency.ts(35,80): error TS2345: Argument of type 'Currency' is not assignable to parameter of type 'object'.
ts/src/test/Exchange/base/test.currency.ts(35,87): error TS18048: 'entry' is possibly 'undefined'.
ts/src/test/Exchange/base/test.currency.ts(37,97): error TS18048: 'entry' is possibly 'undefined'.
ts/src/test/Exchange/base/test.currency.ts(40,26): error TS18048: 'entry' is possibly 'undefined'.
ts/src/test/Exchange/base/test.currency.ts(76,13): error TS7053: Element implicitly has an 'any' type ...
```

TS18048 on `entry` is the compiler independently flagging failure class (a) — it is the deleted `undefined` guard, caught statically. `(76,13)` is the removal of the `// @ts-ignore` above `format['id'] = 123` without giving `format` an index signature.

### What would make this mergeable

The recursion into `networks[]` is a genuinely worthwhile idea and master still carries a `// todo: networks check` marker for it. But it wants to be a **fresh, additive PR on current master**, not this branch:

1. Keep master's `isNative` gating, the `entry === undefined` early return, `safeDict` for `networks`, and the `skipCurrenciesWithoutNetworks` return — none of these are what the PR set out to change.
2. Add only the network-entry loop, with `emptyAllowedFor` for the per-network fields real payloads omit.
3. Drop the `active` invariant, or restrict it to `entry['active'] !== undefined` — and run it against all 89 currency fixtures before proposing it.
4. Regenerate and check the Python/PHP emit with `--test` (not `--baseTests`), and grep the new symbol in the generated file before reading any green.

Happy to re-review a rebased, matrix-clean version. As it stands the branch cannot be merged (conflict) and should not be merged (matrix red in [...]

2026-09-14 11:08 UTC, carlotestor commented
Closing as part of a backlog sweep of conflicting pull requests.

This PR cannot merge (it conflicts with `master`), and the review above found a correctness problem that a rebase on its own would not resolve. The specific finding, with the probe output behind it, is here: https://github.com/ccxt/ccxt/pull/18594#pullrequestreview-5192299405

Thank you for the contribution. The underlying intent may well still be wanted — if you want to pursue it, a fresh branch off current `master` addressing that finding would be the way, and if you think the assessment is wrong please say so and this can be reopened.

2026-09-14 11:08 UTC, closed without merging