fix(tests) - public trade sides
ccxt/ccxt pull request #19121
Opened 2023-09-07 19:16 UTC by ttodua

wip

2024-01-11 10:54 UTC, ttodua commented
waiting for these PRs to be merged: https://github.com/ccxt/ccxt/pulls?q=is%3Apr+is%3Aopen+sort%3Aupdated-desc+in%3Atitle+quick
after that this PR will be ready.

2024-01-18 20:08 UTC, ttodua commented
@carlosmiei this PR is ready to be merged,  non-related issues on travis. 
this is much comprehensive tests for fetchTrades, had revealed buggy exchanges with the help of such tests.

2024-01-20 18:35 UTC, ttodua commented
@carlosmiei whenever you have time to review this? thanks

2024-01-26 17:06 UTC, ttodua commented
tests passes too.
@carlosmiei

2024-01-26 17:22 UTC, carlosmiei commented
I will have to check this in detail, I'm not sure we need to perform those exhaustive tests

2024-01-26 17:23 UTC, ttodua commented
why not? what's bad with exhaustive tests?

2024-01-26 17:24 UTC, carlosmiei commented
> why not? what's bad with exhaustive tests?

As I said I have to check, because this is a trade-off as you know, the more exhaustive the tests over something we don't control are, higher the chance of breaking frequently

2024-01-26 17:40 UTC, ttodua commented
in advance, I can't say for sure. maybe if we see the frequent problem,  maybe then relax/remove?

2024-01-26 17:42 UTC, ttodua commented
> As I said I have to check, because this is a trade-off as you know, the more exhaustive the tests over something we don't control are, higher the chance of breaking frequently

sure sure

2024-03-22 18:30 UTC, ttodua commented
unrelated issues happen, they can be skipped/fixed in other quick small PRs independently if PR is merged

2024-03-22 18:36 UTC, ttodua commented
beside that, this PR is important, as it revealed many exchanges' implementational issues in "trades" (which were being fixed in separate PRs till date) and eventually, as you see all exchanges pass these tests now. These tests will not cause any frequent failures on travis, only rarely, and even in such cases we can add quick skip.

2026-05-15 12:00 UTC, ttodua commented
@carlosmiei ^

2026-07-06 17:28 UTC, ttodua commented on ts/src/test/Exchange/test.fetchTrades.ts
> +    const trades = await exchange.fetchTrades (symbol, undefined, 12000); // lets test with unrealistically high amount
deliberate change to see the error from exchange

2026-08-09 09:49 UTC, carlotestor requested changes
## Summary
Strengthens public-trade assertions (takerOrMaker split, both-sides presence, same-ts price-direction side check) and wires that through the shared trade validator + WS callers. Direction is right, but **Java CI is already red** on this head, and there are a few skip-tests / heuristic issues to fix before merge.

## Correctness
- **Java transpile break (blocking):** New helpers are named `testFetchTradesResponse` / `testFetchTradesStructure` / `testFetchTradesSidesBuySell` / `testFetchTradesSideSequence`. The Java exchange-test post-process rewrites `testX(exchange,` → `TestX.testX(exchange,` unless the name ends with `Helper`. CI fails with `cannot find symbol: TestFetchTradesResponse` (and siblings). Rename helpers to end with `Helper` (same pattern as `testWatchTickersHelper`) or drop the `test` prefix like `fetchTickersHelperTest`.
- **`skip-tests.json` / coinmate:** `orderBook.compareToNextItem` was replaced with a no-op `bid` key, and order-book skip strings were copied into `fetchTrades`. Restore `compareToNextItem` on orderBook; keep only real fetchTrades keys (`emptyResponse` / `sideSequence` / etc.).
- **`sideSequence` ordering:** The heuristic walks array order and assumes same-ts multi-fills are in fill (chrono) order. It still runs when `timestampSort` is skipped. Gate it on ascending timestamp order (or sort a copy first); otherwise reverse-sorted feeds produce false failures — which is why ~39 exchanges already need `sideSequence: "todo check"`.
- **Typo:** vertex `fees: "missingn from structure"` → `missing`.

## Tests / scope
- Public vs private `takerOrMaker` split in `test.trade.ts` is correct and removes the old duplicated check in `fetchTrades`.
- `limit=12000` is aggressive (timeouts / exchange rejects); clamping on kalshi/limitless matches that choice — keep an eye on live flakiness.
- Mass `sideSequence: "todo check"` skips are a large temporary surface; prefer fixing reverse `fetchTrades` sort at the exchange (PR body list) over long-lived skips.

## Labels applied
- Already labeled `enhancement` (left as-is).

## Verdict
**Request changes** — fix the Java helper naming (hard multi-lang break), clean the coinmate skip corruption, and tighten `sideSequence` vs sort-order coupling.

_Automated triage by carlotestor (Hermes ccxt-new-pr-issue-webhook)._

2026-08-09 09:49 UTC, carlotestor commented on ts/src/test/Exchange/test.fetchTrades.ts
> +        await testFetchTradesSideSequence (exchange, skippedProperties, symbol, method, trades);
**Blocking (Java CI):** helpers named `testFetchTradesResponse` / `testFetchTradesStructure` / `testFetchTradesSidesBuySell` / `testFetchTradesSideSequence` are rewritten by `build/javaTranspiler.ts` to `TestFetchTradesResponse.testFetchTradesResponse(...)` etc., inventing classes that do not exist. Live failure: `TestFetchTrades.java: cannot find symbol TestFetchTradesResponse` (and 3 siblings).

Rename so names **end with `Helper`** (see the `name.endsWith('Helper')` skip in javaTranspiler), e.g. `testFetchTradesResponseHelper`, or drop the `test` prefix like `fetchTickersHelperTest` / `fetchTickersAmountsTest`.

2026-08-09 09:49 UTC, carlotestor commented on ts/src/test/Exchange/test.fetchTrades.ts
> +    }
**`sideSequence` assumes array order == fill order** within a same-timestamp multi-fill. This still runs when `timestampSort` is skipped, so reverse-sorted `fetchTrades` feeds invert the price direction and false-fail (hence the large `sideSequence: "todo check"` skip wave).

Gate this check on ascending timestamps (or sort a shallow copy by `timestamp` before the loop), and/or skip automatically when `timestampSort` is in `skippedProperties`.

2026-08-09 09:49 UTC, carlotestor commented on skip-tests.json
> +                "bid":"ask should be less than next ask"
**coinmate skip corruption:** `orderBook.compareToNextItem` was replaced with `"bid"` (not a skip key `test.orderBook` honors — it only checks `compareToNextItem` / `compareToZero` / `spread`). The old order-book reason strings were also pasted into `fetchTrades` as `compareToNextItem` / `bid`, which fetchTrades never reads.

Restore `orderBook.compareToNextItem`, and keep only real fetchTrades keys here (e.g. `emptyResponse`, `sideSequence`).

2026-08-09 09:49 UTC, carlotestor commented on skip-tests.json
> +                "fees": "missingn from structure",
Typo: `"missingn from structure"` → `"missing from structure"` (copied from pre-existing timex wording; fix while touching vertex).

2026-08-09 10:25 UTC, ttodua commented on ts/src/test/Exchange/test.fetchTrades.ts
> +        await testFetchTradesSideSequence (exchange, skippedProperties, symbol, method, trades);
done

2026-08-09 10:26 UTC, ttodua commented on skip-tests.json
> +                "bid":"ask should be less than next ask"
done

2026-08-09 10:27 UTC, ttodua commented on skip-tests.json
> +                "fees": "missingn from structure",
done

2026-08-09 10:33 UTC, ttodua commented on ts/src/test/Exchange/test.fetchTrades.ts
> +    }
it's done intentionally

2026-09-05 11:37 UTC, closed without merging