feat(mexc): watchOrderBook - uses limit parameter
ccxt/ccxt pull request #20872
Opened 2024-01-18 22:19 UTC by samgermain

Currently receiving this response when trying to add the depth. I do not receive this error message when subscribing without the depth

```
2024-01-18T22:05:32.067Z
Node.js: v18.12.0
CCXT v4.2.15
mexc.watchOrderBook (SOL/USDT, 10)
2024-01-18T22:05:35.331Z connecting to wss://wbs.mexc.com/ws
2024-01-18T22:05:35.935Z onUpgrade
2024-01-18T22:05:35.936Z onOpen
2024-01-18T22:05:35.937Z sending {
  method: 'SUBSCRIPTION',
  params: [ 'spot@public.increase.depth.v3.api@SOLUSDT@10' ]
}
2024-01-18T22:05:36.167Z onMessage { id: 0, code: 0, msg: 'no subscription success' }
2024-01-18T22:05:45.938Z sending { method: 'ping' }
2024-01-18T22:05:46.155Z onMessage { id: 0, code: 0, msg: 'PONG' }
2024-01-18T22:05:55.939Z sending { method: 'ping' }
2024-01-18T22:05:56.137Z onMessage { id: 0, code: 0, msg: 'PONG' }
2024-01-18T22:06:05.932Z onClose CloseEvent {
  [Symbol(kTarget)]: <ref *1> WebSocket {
    _events: [Object: null prototype] {
      open: [Function],
      message: [Function],
      error: [Function],
      close: [Function],
      ping: [Function: bound onPing],
      pong: [Function: bound onPong],
      upgrade: [Function: bound onUpgrade]
    },
    _eventsCount: 7,
    _maxListeners: undefined,
    _binaryType: 'nodebuffer',
    _closeCode: 1005,
    _closeFrameReceived: true,
    _closeFrameSent: true,
    _closeMessage: <Buffer >,
    _closeTimer: Timeout {
      _idleTimeout: -1,
      _idlePrev: null,
      _idleNext: null,
      _idleStart: 42388,
      _onTimeout: null,
      _timerArgs: undefined,
      _repeat: null,
      _destroyed: true,
      [Symbol(refed)]: true,
      [Symbol(kHasPrimitive)]: false,
      [Symbol(asyncId)]: 3393,
      [Symbol(triggerId)]: 3355
    },
    _extensions: {},
    _paused: false,
    _protocol: '',
    _readyState: 3,
    _receiver: Receiver {
      _writableState: [WritableState],
      _events: [Object: null prototype] {},
      _eventsCount: 0,
      _maxListeners: undefined,
      _binaryType: 'nodebuffer',
      _extensions: {},
      _isServer: false,
      _maxPayload: 104857600,
      _skipUTF8Validation: false,
      _bufferedBytes: 0,
      _buffers: [],
      _compressed: false,
      _payloadLength: 0,
      _mask: undefined,
      _fragmented: 0,
      _masked: false,
      _fin: true,
      _opcode: 8,
      _totalPayloadLength: 0,
      _messageLength: 0,
      _fragments: [],
      _state: 0,
      _loop: false,
      [Symbol(kCapture)]: false,
      [Symbol(websocket)]: [Circular *1]
    },
    _sender: Sender {
      _extensions: {},
      _socket: [TLSSocket],
      _firstFragment: true,
      _compress: false,
      _bufferedBytes: 0,
      _deflating: false,
      _queue: []
    },
    _socket: TLSSocket {
      _tlsOptions: [Object],
      _secureEstablished: true,
      _securePending: false,
      _newSessionPending: false,
      _controlReleased: true,
      secureConnecting: false,
      _SNICallback: null,
      servername: 'wbs.mexc.com',
      alpnProtocol: false,
      authorized: true,
      authorizationError: null,
      encrypted: true,
      _events: [Object: null prototype],
      _eventsCount: 6,
      connecting: false,
      _hadError: false,
      _parent: null,
      _host: 'wbs.mexc.com',
      _closeAfterHandlingError: false,
      _readableState: [ReadableState],
      _maxListeners: undefined,
      _writableState: [WritableState],
      allowHalfOpen: false,
      _sockname: null,
      _pendingData: null,
      _pendingEncoding: '',
      server: undefined,
      _server: null,
      ssl: null,
      _requestCert: true,
      _rejectUnauthorized: true,
      parser: null,
      _httpMessage: null,
      timeout: 0,
      write: [Function: writeAfterFIN],
      [Symbol(res)]: null,
      [Symbol(verified)]: true,
      [Symbol(pendingSession)]: null,
      [Symbol(async_id_symbol)]: 3355,
      [Symbol(kHandle)]: null,
      [Symbol(lastWriteQueueSize)]: 0,
      [Symbol(timeout)]: null,
      [Symbol(kBuffer)]: null,
      [Symbol(kBufferCb)]: null,
      [Symbol(kBufferGen)]: null,
      [Symbol(kCapture)]: false,
      [Symbol(kSetNoDelay)]: true,
      [Symbol(kSetKeepAlive)]: false,
      [Symbol(kSetKeepAliveInitialDelay)]: 0,
      [Symbol(kBytesRead)]: 574,
      [Symbol(kBytesWritten)]: 364,
      [Symbol(connect-options)]: [Object],
      [Symbol(websocket)]: undefined
    },
    _bufferedAmount: 0,
    _isServer: false,
    _redirects: 0,
    _url: 'wss://wbs.mexc.com/ws',
    _req: null,
    [Symbol(kCapture)]: false
  },
  [Symbol(kType)]: 'close',
  [Symbol(kCode)]: 1005,
  [Symbol(kReason)]: '',
  [Symbol(kWasClean)]: true
}
NetworkError connection closed by remote server, closing code 1005
---------------------------------------------------
[NetworkError] connection closed by remote server, closing code 1005

    at onClose        …samgermain/Documents/CCXT/ccxt/ts/src/base/ws/Client.ts:273                                                          
    at callListener   ws/lib/event-target.js:290                                    listener.call(thisArg, event);                          
    at onClose        ws/lib/event-target.js:220                                    callListener(handler, this, event);                     
    at emit           node:events:513                                                                                                       
    at emit           node:domain:489                                                                                                       
    at emitClose      ws/lib/websocket.js:260                                       this.emit('close', this._closeCode, this._closeMessage);
    at socketOnClose  ws/lib/websocket.js:1272                                      websocket.emitClose();                                  
    at emit           node:events:525                                                                                                       
    at emit           node:domain:489                                                                                                       
    at                node:net:313                                                                                                          

connection closed by remote server, closing code 1005
```

fixes: #20860

2024-05-24 16:44 UTC, carlosmiei commented on ts/src/pro/mexc.ts
> +                messageHash += ':' + limit;
@samgermain this breaks in python, we must be careful with these things

```
 p mexc watchOrderBook "BTC/USDT" 5 > out.txt
/Users/cjg/Git/ccxt10/ccxt/examples/py/cli.py:124: SyntaxWarning: invalid escape sequence '\s'
  call_reg = "\s*(\w+)\s*\.\s*(\w+)\s*\(([^()]*)\)"
Traceback (most recent call last):
  File "/Users/cjg/Git/ccxt10/ccxt/examples/py/cli.py", line 246, in <module>
    asyncio.run(main())
  File "/opt/homebrew/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/cjg/Git/ccxt10/ccxt/examples/py/cli.py", line 225, in main
    result = await result
             ^^^^^^^^^^^^
  File "/Users/cjg/Git/ccxt10/ccxt/python/ccxt/pro/mexc.py", line 364, in watch_order_book
    messageHash += ':' + limit
                   ~~~~^~~~~~~
TypeError: can only concatenate str (not "int") to str
```

2024-05-24 16:45 UTC, carlosmiei commented on ts/src/pro/mexc.ts
> +                messageHash += ':' + limit;
also if we add the limit to the messageHash, then we would need to adjust the resolving as well

2024-05-24 16:46 UTC, carlosmiei requested changes
this is not working,

2024-05-24 21:48 UTC, samgermain commented
@carlosmiei It looks like none of the responses are resolved until a response with `lastUpdateId` is returned, probably because `handleOrderBookSubscription` doesn't needs to do some necessary action (is it that `        this.orderbooks[symbol] = this.orderBook ({});` needs to be called first?). I ran the method in verbose mode and there were 140 responses from the exchange before a response was returned in the format below

```
 {
  "lastUpdateId":2603367804,
  "bids":[
    ["167.45","152.85"],["167.44","200.95"], ...
  ],
    "asks":[
      ["167.46","431.08"],["167.47","364.63"], ...
    ],
    "timestamp":1716586891561
  }
 ```
 
 ---------
 
 This happens on master also and is not a problem with this PR

2026-09-13 21:29 UTC, carlotestor reviewed
## Review: `feat(mexc): watchOrderBook - uses limit parameter`

Merge gate: 🔴

Category: **REBASE (and WRONG APPROACH for the spot leg)** — verified at head `e30a909dbfe7004b33654639ae49d9be7e4ebad2` in a detached sandbox.

### 1. What conflicts

`git merge-tree --write-tree origin/master e30a909` exits **1** with `CONFLICT (content): Merge conflict in ts/src/pro/mexc.ts` — **3 conflict hunks**, and every one of them is a *semantic* disagreement, not carrier churn:

| Hunk | master | this branch |
|---|---|---|
| imports (line 6) | `ArgumentsRequired, AuthenticationError, NotSupported` | `AuthenticationError, BadRequest` |
| `watchOrderBook` body (766–819) | `spot@public.aggre.depth.v3.api.pb@<frequency>@<id>` + `handleOptionAndParams(params, 'watchOrderBook', 'frequency', '100ms')` | `spot@public.increase.depth.v3.api@<id>` / `spot@public.limit.depth.v3.api@<id>@<limit>` |
| `handleSubscriptionStatus` methods map (2147) | `'public.aggre.depth.v3.api.pb'` | `'public.limit.depth.v3.api'` |

The branch base is `ff48337319d` — **17394 commits** behind `origin/master`. The whole spot order-book transport has been replaced underneath it: master now uses the protobuf `aggre.depth` stream with a `params.frequency` knob, and `increase.depth.v3.api` (this PR's baseline channel) is no longer subscribed anywhere.

### 2. Not landed, not superseded — but no longer applicable as written

`grep` of master's `ts/src/pro/mexc.ts` shows `watchOrderBook (symbol, limit, params)` still ignores `limit` for channel selection (the arg is only used by the trailing `orderbook.limit ()`), so the *feature* is genuinely absent from master. It is not SUPERSEDED. But the mechanism is: the spot channel the PR forks from is gone, and master additionally grew `unWatchOrderBook` (line 1907), which this branch predates entirely.

### 3. Correctness findings at head

I transpiled the head's own `ts/src/pro/mexc.ts` (the committed `js/` in the tree is master-generated and would have given a false read) and drove `handleOrderBook` with injected frames on an offline `setMarkets()` exchange.

**(a) Loud failure on an unsupported limit — this part is right.** `watchOrderBook('BTC/USDT', 7)` and `(…, 100)` both raise:

```
BadRequest  mexc watchOrderBook () limit argument can only be 5, 10 or 20
```

and `5 / 10 / 20` matches MEXC's documented `levels` set for the partial-depth stream. Also worth crediting: unlike the sibling limit PRs in this cluster, the limit here is the **positional argument**, not a `handleOption`-read `params` key, so the `params.adjustLimit`-is-dead defect class from #26562 does **not** apply here.

**(b) The swap leg's `limit` is silently dropped by the venue.** The PR adds `requestParams['limit'] = limit` to the `sub.depth` subscribe frame. MEXC's futures `sub.depth` accepts **only** `{ "symbol": "BTC_USDT" }`; the bucketing variant is a different method (`sub.depth.step`, param `step`). So the swap path sends `{"symbol":"BTC_USDT","limit":7}`, gets the full incremental stream back, and the caller's limit is honoured only by the client-side `orderbook.limit ()` — i.e. exactly the pre-PR behaviour, with **no** validation and no error. The JSDoc change to `@param {int} [limit] 5, 10, or 20` is therefore wrong for swap markets: 7 throws on spot and is accepted-then-ignored on swap.

**(c) Spot: a full-snapshot stream is fed into the incremental merger. This corrupts the book.** `spot@public.limit.depth.v3.api` pushes a **complete top-N snapshot** each tick; `increase.depth` pushes diffs. The PR routes the new channel to the same `handleOrderBook` → `handleDelta` → `handleBooksideDelta`, which only `store`s the rows present in the frame and never clears absent levels. Two consecutive top-5 snapshots whose prices have moved:

```
tick1 asks [[101,1],[102,1],[103,1],[104,1],[105,1]]
tick2 asks [[101,1],[102,1],[103,1],[104,1],[105,1],[111,1],[112,1],[113,1],[114,1],[115,1]]
tick2 bids [[109,1],[108,1],[107,1],[106,1],[105.5,1],[99,1],[98,1],[97,1],[96,1],[95,1]]
depth asks/bids = 10 10   (the exchange pushed 5 each)
watchOrderBook returns best ask [101,1]  best bid [109,1]
```

The returned book is **crossed** (bid 109 > ask 101) and twice the requested depth, and it degrades monotonically: nothing ever removes the stale tick-1 levels because a snapshot stream expresses removal by *omission*, not by a zero-size row. A snapshot channel needs a replace-the-side handler (`orderbook.reset ()` / rebuild both sides per frame), not `handleDelta`.

**(d) The `messageHash` suffix collides with master's channel layout.** `handleOrderBook` derives the suffix as `channel.split('@')[3]`. On the PR's own channel that is the depth (`…@BTCUSDT@10` → `"10"`). On **master's** channel it is the market id:

```
'spot@public.aggre.depth.v3.api.pb@100ms@BTCUSDT'.split('@')[3] === 'BTCUSDT'
→ messageHash 'orderbook:BTC/USDT:BTCUSDT'
```

So the positional extraction does not survive the rebase — after merging onto master it would suffix every spot order-book hash with the raw market id, which `watchOrderBook`'s `'orderbook:' + symbol` never subscribes to, and the future would never resolve. This is a concrete instance of why (1) is not mechanical.

**(e) watch/unWatch topic parity.** `unWatchOrderBook` does not exist on this branch, so there is no mismatch *here* — but master's `unWatchOrderBook` (line 1919) builds the `aggre.depth` topic and the plain `'unsubscribe:orderbook:' + symbol` hash with no limit suffix. Any rebase must carry the limit into **both** the subscribe topic and the unsubscribe topic/hash, or an `unWatchOrderBook` on a limited subscription will unsubscribe a topic that was never subscribed — the defect shape flagged on #26663.

### Verification performed

- `git merge-tree --write-tree origin/master e30a909` → exit 1, 3 conflict hunks enumerated above; merge base `ff48337319d`, 17394 commits behind.
- Sparse sandbox detached at `e30a909`, `node_modules` symlinked, no writes to the shared checkout.
- Head TS transpiled with `typescript@5.4.5` into `/tmp` and swapped into `js/src/pro/mexc.js` for the probe (restored afterwards; `git status --porcelain` clean).
- Offline probe via `setMarkets()` from `ts/src/test/static/markets/mexc.json`, no network, no credentials; frames injected directly into `handleMessage`/`handleOrderBook`.
- MEXC docs read for both legs: spot *Partial Book Depth Streams* (`levels` = 5/10/20) and futures *Order book depth* (`sub.depth`, param `symbol` only).

### What would make this mergeable

1. Rebase onto current master and re-express the spot leg on top of `aggre.depth.v3.api.pb` (or whatever channel MEXC now documents for limited depth — note the docs now show the `.pb` suffix on `limit.depth` too: `spot@public.limit.depth.v3.api.pb@<symbol>@<level>`, with payload keys `publicLimitDepths` / `price` / `quantity`, not `d`/`p`/`v`).
2. Give the snapshot channel its own handler that **replaces** both sides per frame instead of reusing `handleDelta`.
3. Derive the depth suffix by name rather than by `split('@')[3]`.
4. Either validate/route the swap `limit` against a channel that actually supports it, or drop it from the request and say in the JSDoc that swap limits are applied client-side.
5. Mirror the limit into `unWatchOrderBook`'s topic and hash.

Happy to re-gate once it is rebased — the validation shape in (a) is the good part and worth keeping.

2026-09-14 08:27 UTC, carlotestor commented
Closing as part of a backlog sweep of conflicting pull requests.

This PR cannot merge (it conflicts with `master`), and the review above found a correctness problem that a rebase on its own would not resolve. The specific finding, with the probe output behind it, is here: https://github.com/ccxt/ccxt/pull/20872#pullrequestreview-5192307618

Thank you for the contribution. The underlying intent may well still be wanted — if you want to pursue it, a fresh branch off current `master` addressing that finding would be the way, and if you think the assessment is wrong please say so and this can be reopened.

2026-09-14 08:27 UTC, closed without merging